apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-js
  labels:
    app: my-app-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-js
  template:
    metadata:
      labels:
        app: my-app-js
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app-js
        image: 086241318794.dkr.ecr.eu-central-1.amazonaws.com/my-app-js:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
